export interface User {
    id: string,
    lastName: string,
    firstName: string,
    email: string,
    password: string,
    userName: string,
    birthate: Date,
    genre: string,
    ori_sex: string,
    bio: string,
    score: string,
    city: string,
    latitude: string,
    longitude: string,
    acc_valid: boolean,
    acc_comp: string,
    link: string,
}